import Header from "@/components/Header";
import "./globals.scss";
import Main from "@/components/Main";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />

        <Main>{children}</Main>
      </body>
    </html>
  );
}
