// context
import { AppContextProvider } from "@/context/AppContext";

// components
import Header from "@/components/Header";
import Main from "@/components/Main";
import Footer from "@/components/Footer";

// styles
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <Header />

          <Main>{children}</Main>

          <Footer />
        </AppContextProvider>
      </body>
    </html>
  );
}
